stages:
  - build
  - deploy

workflow:
  rules:    
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables: 
        DOCKER_TAGS: "latest"
        ENV: prod
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      variables: 
        DOCKER_TAGS: "test-develop"
        ENV: test               
    - if: '$CI_COMMIT_TAG'
      variables: 
        DOCKER_TAGS: $CI_COMMIT_TAG
        ENV: prod        

build:
  stage: build
  environment: ${ENV}
  tags:
    - SIG
    - dind    
  image:
    name: ${NEXUS_PROXY_URL}/docker:latest
  services:
    - name: ${NEXUS_PROXY_URL}/docker:dind
      alias: docker
  variables:    
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:    
    - cp ${ENV_FILE} $CI_PROJECT_DIR/.env
  script:
    - cd $CI_PROJECT_DIR
    - docker login -u ${NEXUS_ACCOUNT_LOGIN} -p ${NEXUS_ACCOUNT_PWD} ${NEXUS_DOCKER_URL}
    - docker login -u ${NEXUS_ACCOUNT_LOGIN} -p ${NEXUS_ACCOUNT_PWD} ${NEXUS_PROXY_URL}
    - docker build -t ${NEXUS_DOCKER_URL}/sig/${CI_PROJECT_NAME}:${DOCKER_TAGS} .
    - docker push ${NEXUS_DOCKER_URL}/sig/${CI_PROJECT_NAME}:${DOCKER_TAGS}
  #rules:      
    #- if: '$CI_COMMIT_REF_NAME == "develop"'
    #  when: manual
    #- if: '$CI_COMMIT_REF_NAME == "main"'
    #- if: '$CI_COMMIT_TAG'      

#Déploiement avec Ansible avec les variables contenues dans .deploy/inventory
deploy-ansible:
  stage: deploy
  tags: 
    - SIG
    - deploy
  image: nexus.si.rennes.fr:5002/sig/ansible-runner:latest
  script:    
    - ansible-galaxy collection install -r .deploy/requirements.yml
    - chmod 600 $GITLABRUNNERSIG_KEY    
    - | 
      ansible-playbook \
        -i .deploy/inventory \
        -u $REMOTE_USER --private-key $GITLABRUNNERSIG_KEY .deploy/playbook.yml \
        --extra-vars \
          "CI_PROJECT_DIR=$CI_PROJECT_DIR \
            CI_PROJECT_NAME=$CI_PROJECT_NAME \            
            DOCKER_TAGS=$DOCKER_TAGS \
            NEXUS_ACCOUNT_LOGIN=$NEXUS_ACCOUNT_LOGIN \
            NEXUS_ACCOUNT_PWD=$NEXUS_ACCOUNT_PWD \
            NEXUS_DOCKER_URL=$NEXUS_DOCKER_URL \
            ENV=$ENV"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
      when: manual
    #- if: '$CI_COMMIT_REF_NAME == "develop"'
    #  when: manual
    - if: '$CI_COMMIT_TAG'
      when: manual
