version: '3.7'
services:
  api-3D:
      build: ./
      image: sigrennesmetropole/api-3d:${TAG:-latest}
      ports:
        - 8080:8080
      environment:
        # TODO ajouter les variables d'environnements
        TEST: "true"
      init: true
  3dciytdb:
      image: 3dcitydb/3dcitydb-pg:13-3.2-4.2.0-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER          : admin
        POSTGRES_PASSWORD      : password
      init: true