version: '3.7'
services:
  api-3D:
      restart: unless-stopped
      container_name: api-3D-${environnement}
      image: ghcr.io/sigrennesmetropole/api-3d:${version}
      ports:
        - 127.0.0.1:${port}:8080
      volumes:
        - ${impexp_local_path}:/etc/impexp
        - ${download_file_path}:/usr/src/app/src/files
      environment:
        IMPORTER_EXPORTER_PATH: /etc/impexp
        EXPORTER_SAVE_PATH: /usr/src/app/src/export/
        DISPLAY: :0.0
        DB_USERNAME: ${DB_USERNAME}
        DB_HOST: ${DB_HOST}
        DB_DATABASE: ${DB_DATABASE}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_PORT: ${DB_PORT}
        HTTP_PROXY: ${HTTP_PROXY:-}
        HTTPS_PROXY: ${HTTP_PROXY:-}
        http_proxy: ${HTTP_PROXY:-}
        https_proxy: ${HTTP_PROXY:-}
        ftp_proxy: ${HTTP_PROXY:-}
        PROXY_HOST: ${PROXY_HOST}
        PROXY_PORT: ${PROXY_PORT}
        BBOX_MAX_SIZE: ${BBOX_MAX_SIZE:-10}
        DB_SCHEMA_EVOLUTION: ${DB_SCHEMA_EVOLUTION}
        DB_VIEW_ADDED_BUILDINGS: ${DB_VIEW_ADDED_BUILDINGS}
        DB_VIEW_MODIFIED_BUILDINGS: ${DB_VIEW_MODIFIED_BUILDINGS}
        DB_VIEW_DELETED_BUILDINGS: ${DB_VIEW_DELETED_BUILDINGS}
        PG_MAX_NB_CONNECTIONS: ${PG_MAX_NB_CONNECTIONS}
        PG_CONNECT_TIMEOUT: ${PG_CONNECT_TIMEOUT}
        PG_ROWS_LIMIT: ${PG_ROWS_LIMIT}
        3faad540-1cc3-4224-a326-2bf1e8f550bc: 3d_rennesmetropole_terrain_maillage.zip
        72bca5d3-ee31-4a83-8a92-837e8d048cc3: 3d_rennesmetropole_terrain_raster.zip
        0d75bd55-be52-4493-9bd7-f623c49f6531: 3d_rennesmetropole_batis_cityjson.zip
        7f742cc7-97db-4619-bcf2-fc8451c22015: 3d_rennesmetropole_irradiance.zip
        1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9: 3d_rennesmetropole_bibli_arbres.zip
        1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9: 3d_rennesmetropole_bibli_mobilier_urbain.zip
        FILES_IDS: 3faad540-1cc3-4224-a326-2bf1e8f550bc,72bca5d3-ee31-4a83-8a92-837e8d048cc3,0d75bd55-be52-4493-9bd7-f623c49f6531,7f742cc7-97db-4619-bcf2-fc8451c22015,1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9,1acd23ad-c4b1-4ccb-83c6-33e6ef2214e9
      init: true
