version: '3.7'
services:
  api-3D-recette:
      build: ../
      image: sigrennesmetropole/api-3d:${TAG:-latest}
      ports:
        - 28080:8080
      volumes:
        - C:\Softs\3DCityDB-Importer-Exporter-5.1.0:/etc/impexp
        - C:\Projets\RM\api3d-fichiers statiques:/usr/src/app/src/files
      environment:
        DB_USERNAME: admin
        DB_HOST: 3dciytdb
        DB_DATABASE: citydb
        DB_PASSWORD: password
        DB_PORT: 5432
        PG_MAX_NB_CONNECTIONS: 10
        PG_CONNECT_TIMEOUT: 1000
        PG_ROWS_LIMIT: 2000000000
        DB_VIEW_ADDED_BUILDINGS: v_batis_ajout
        DB_VIEW_MODIFIED_BUILDINGS: v_batis_modif
        DB_VIEW_DELETED_BUILDINGS: v_batis_suppr
        IMPORTER_EXPORTER_PATH: /etc/impexp
        DISPLAY: :0.0
        EXPORTER_SAVE_PATH: /usr/src/app/src/export/
        HTTP_PROXY: http://fr-proxy.resultinfra.com:3128/
        HTTPS_PROXY: http://fr-proxy.resultinfra.com:3128/
        http_proxy: http://fr-proxy.resultinfra.com:3128/
        https_proxy: http://fr-proxy.resultinfra.com:3128/
        ftp_proxy: http://fr-proxy.resultinfra.com:3128/
        3faad540-1cc3-4224-a326-2bf1e8f550bc: 3d_rennesmetropole_terrain_maillage.zip
        72bca5d3-ee31-4a83-8a92-837e8d048cc3: 3d_rennesmetropole_terrain_raster.zip
        0d75bd55-be52-4493-9bd7-f623c49f6531: 3d_rennesmetropole_batis_cityjson.zip
        7f742cc7-97db-4619-bcf2-fc8451c22015: empty.zip
        FILES_IDS: 3faad540-1cc3-4224-a326-2bf1e8f550bc,72bca5d3-ee31-4a83-8a92-837e8d048cc3,0d75bd55-be52-4493-9bd7-f623c49f6531,7f742cc7-97db-4619-bcf2-fc8451c22015
      init: true
  api-3D-integration:
      build: ../
      image: sigrennesmetropole/api-3d:${TAG:-latest}
      ports:
        - 18080:8080
      volumes:
        - C:\Softs\3DCityDB-Importer-Exporter-5.1.0:/etc/impexp
        - C:\Projets\RM\api3d-fichiers statiques:/usr/src/app/src/files
      environment:
        DB_USERNAME: admin
        DB_HOST: 3dciytdb
        DB_DATABASE: citydb
        DB_PASSWORD: password
        DB_PORT: 5432
        PG_MAX_NB_CONNECTIONS: 10
        PG_CONNECT_TIMEOUT: 1000
        PG_ROWS_LIMIT: 2000000000
        DB_VIEW_ADDED_BUILDINGS: v_batis_ajout
        DB_VIEW_MODIFIED_BUILDINGS: v_batis_modif
        DB_VIEW_DELETED_BUILDINGS: v_batis_suppr
        IMPORTER_EXPORTER_PATH: /etc/impexp
        DISPLAY: :0.0
        EXPORTER_SAVE_PATH: /usr/src/app/src/export/
        HTTP_PROXY: http://fr-proxy.resultinfra.com:3128/
        HTTPS_PROXY: http://fr-proxy.resultinfra.com:3128/
        http_proxy: http://fr-proxy.resultinfra.com:3128/
        https_proxy: http://fr-proxy.resultinfra.com:3128/
        ftp_proxy: http://fr-proxy.resultinfra.com:3128/
        3faad540-1cc3-4224-a326-2bf1e8f550bc: 3d_rennesmetropole_terrain_maillage.zip
        72bca5d3-ee31-4a83-8a92-837e8d048cc3: 3d_rennesmetropole_terrain_raster.zip
        0d75bd55-be52-4493-9bd7-f623c49f6531: 3d_rennesmetropole_batis_cityjson.zip
        7f742cc7-97db-4619-bcf2-fc8451c22015: empty.zip
        FILES_IDS: 3faad540-1cc3-4224-a326-2bf1e8f550bc,72bca5d3-ee31-4a83-8a92-837e8d048cc3,0d75bd55-be52-4493-9bd7-f623c49f6531,7f742cc7-97db-4619-bcf2-fc8451c22015
      init: true
  3dciytdb:
      image: 3dcitydb/3dcitydb-pg:13-3.2-4.2.0-alpine
      ports:
        - 5432:5432
      environment:
        POSTGRES_USER          : admin
        POSTGRES_PASSWORD      : password
        POSTGRES_DB: citydb
        SRID: 3948
        HEIGHT_EPSG: 5720
      init: true
  nginx:
    image: nginx:mainline-alpine
    container_name: front_nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/tls:/etc/tls
      - ./impexp_data:/data
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"